NDefines.NGame.START_DATE = "2027.3.1.1"                                        -- It's a canon event
NDefines.NGame.END_DATE = "2077.1.1.1"                                          -- I myk fajrancik, czas na Falloucika
NDefines.NGame.MAP_SCALE_PIXEL_TO_KM = 0.2450                                   -- Yes, we also did the math
NDefines.NDiplomacy.NUM_DAYS_TO_ENABLE_KICKING_NEW_MEMBERS_OF_FACTION = 30      -- Nie wiem czemu ale można kogos wyjebać z frakcji po 30 dniach
NDefines.NDiplomacy.NUM_DAYS_TO_ENABLE_REINVITE_KICKED_NATIONS = 30             -- I z powrotem ich zaprosić po kolejnych 30, tylko ze kurwa mamy wylaczone to xd
NDefines.NDiplomacy.NOT_READY_FOR_WAR_BASE = -10                                -- AI nie powinno się az tak srać gdy dostaje call to war a nie jest ubrane
NDefines.NDiplomacy.FRONT_IS_DANGEROUS = -10                                    -- No nie bój się pizdo, dołączaj do wojny
NDefines.NCountry.MIN_FOCUSES_FOR_CONTINUOUS = 5                                -- Minimalna liczba focusów wymagana do odblokowania continuosów
NDefines.NCountry.MIN_STABILITY = -1.0                                          -- Mamy -100% stabilności...w vanillce jest min 0%
NDefines.NCountry.POPULATION_YEARLY_GROWTH_BASE = 0.005                         -- Przyrost naturalny populacji
NDefines.NPolitics.BASE_POLITICAL_POWER_INCREASE = 1.75                         -- Podstawowy przyrost PP
NDefines.NResistance.GARRISON_MANPOWER_REINFORCEMENT_SPEED = 200.0              -- Liczba o którą się odnawiają manpowerem garnizony, zmniejszona bo jednostki mamy mniejsze
NDefines.NProduction.MIN_POSSIBLE_TRAINING_MANPOWER = 10000                     -- How many deployment lines minimum can be training (co kurwa? to nie powinno być maximum ty szwedzki pachołku?)
NDefines.NResistance.COMPLIANCE_GROWTH_BASE	 = 0.2                              -- Podstawowy przyrost compliance
NDefines.NResistance.RESISTANCE_GROWTH_BASE	 = 0.05                             -- Podstawowy przyrost resistance
NDefines.NResistance.FOREIGN_MANPOWER_MIN_THRESHOLD = 500                       -- Jaki kurwa manpower transfer, co wy pierdolicie?
NDefines.NBuildings.INFRASTRUCTURE_RESOURCE_BONUS = 0                           -- Ten jebany bonus do surowców z infrastruktury
NDefines.NBuildings.SUPPLY_ROUTE_RESOURCE_BONUS = 0                             -- To samo tylko że z supply routów? Kurwa, jak kupujesz to kupujesz, nikt Ci nie dorzuci dodatkowego węgla debilu
NDefines.NMilitary.ARMOR_VS_AVERAGE = 0.3                                       -- jakiś bełkot (how to weight in highest armor & pen vs the division average)
NDefines.NMilitary.DIVISION_SIZE_FOR_XP = 4                                     -- ile batalionów powinna mieć jednostka żeby się liczyła jako pełnoprawna (coś do expa)
NDefines.NMilitary.PLAN_EXECUTE_CAREFUL_LIMIT = 100	                            -- coś z battle planami
NDefines.NMilitary.PLAN_EXECUTE_BALANCED_LIMIT = 25	                            -- coś z battle planami
NDefines.NMilitary.PLAN_EXECUTE_RUSH = 0                                        -- coś z battle planami
NDefines.NMilitary.FIELD_EXPERIENCE_SCALE = 0.0015	                            -- coś z expem
NDefines.NMilitary.LEADER_EXPERIENCE_SCALE = 0.5                                -- coś z expem
NDefines.NMilitary.EXPERIENCE_COMBAT_FACTOR = 0.2                               -- coś z expem
NDefines.NMilitary.PLAN_SPREAD_ATTACK_WEIGHT = 16                               -- ponoć rozszerzanie frontu
NDefines.NMilitary.PLAYER_ORDER_PLANNING_DECAY = 0.01                           -- to jest hit, jebanie gracza za to że mikruje XDDDDDDDDDDDDD
NDefines.NMilitary.OUT_OF_SUPPLY_ATTRITION = 0.25                               -- max attrition gdy nie masz supli                               
NDefines.NMilitary.WAR_SCORE_LOSSES_RATIO = 4                                   -- war score za każde 1000 trupów (chyba się dobrze skaluje)
NDefines.NMilitary.WAR_SCORE_PROVINCE_FACTOR = 4                                -- war score za prowki ale tylko za jej pierwsze zdobycie????
NDefines.NMilitary.VPS_FOR_HISTORY_ENTRY = 10                                   -- za jaki vp jednostka dostaje medal
NDefines.NMilitary.VPS_FOR_HIGH_HISTORY_ENTRY = 30                              -- za jaki vp jednostka dostaje virtuti militari 
NDefines.NMilitary.PLAN_MIN_AUTOMATED_EMPTY_POCKET_SIZE = 10                    -- kociołki panoramixa
NDefines.NAI.MIN_INVASION_PLAN_VALUE_TO_EXECUTE = 0.05                          -- minimalny szacunek sił do puszczenia inwazji
NDefines.NAI.MIN_INVASION_ORG_FACTOR_TO_EXECUTE = 0.4                           -- minimalna organizacja do puszczenia inwazji
NDefines.NAI.NAVAL_MISSION_INVASION_BASE = 2000                                 -- jakieś punkty, ale kurwa nie wiem do czego
NDefines.NAI.AREA_DEFENSE_SETTING_VP = true
NDefines.NAI.AREA_DEFENSE_SETTING_COASTLINES = false
NDefines.NAI.MAX_DISTANCE_NAVAL_INVASION = 2000.0                                -- te wyżej to chuj wie, ale to maksymalny dystans inwazji morskiej
NDefines.NAI.NAVAL_MISSION_DISTANCE_BASE = 4500
NDefines.NAI.AGGRESSIVENESS_BONUS_FOR_FRONTS_THAT_ARE_ON_HIGH_AGGRESSIVENESS = -0.6 -- UGRYŹ, ZAGRYŹ
NDefines.NAI.AGGRESSIVENESS_CHECK_BASE = 1                                      -- Baza - pisał Stalin posyłając cały swój front na aggresive stance
NDefines.NAI.AGGRESSIVENESS_CHECK_CAREFUL = 0.3                                 -- OSTROŻNIE!
NDefines.NAI.FRONT_EVAL_UNIT_SUPPLY_AND_ORG_LACK_IMPACT = 0.5                   -- URRRAAAAAAAAAAAAAAAAAA
NDefines.NAI.PLAN_VALUE_TO_EXECUTE = -0.7
NDefines.NAI.DEPLOY_MIN_TRAINING_SURRENDER_FACTOR = 0.4
NDefines.NAI.DEPLOY_MIN_EQUIPMENT_SURRENDER_FACTOR = 0.7
NDefines.NAI.EASY_TARGET_FRONT_IMPORTANCE = 15
NDefines.NAI.ATTACK_HEAVILY_DEFENDED_LIMIT = 0.2
NDefines.NAI.PLAN_ACTIVATION_SUPERIORITY_AGGRO = 1.5                            -- zraz obranego planu nie zawracaj w fallback line, nie opuszczaj wiary w force attack
NDefines.NAI.DEPLOY_MIN_TRAINING_WAR_FACTOR = 0.6                                   
NDefines.NSupply.VP_TO_SUPPLY_BASE = 0.35                                       -- halo baza, jakiś vp się tu kręci
NDefines.NMilitary.BORDER_WAR_VICTORY = 0.65                                    -- przy jakim balansie wygrywamy border wara (jest niski bo to głównie lorowe rzeczy)
NDefines.NMilitary.BORDER_WAR_WIN_DAYS_AGAINST_EMPTY_OPPONENTS = 7              -- nikt nie przyszedł na border wara ja pierdole
NDefines.NSupply.MAX_RAILWAY_LEVEL = 5                                          -- sram na ciebie pulpecie skandynawski, to nie działa
