NDefines.NGame.START_DATE = "2027.3.1.1"                                        -- It's a canon event
NDefines.NGame.END_DATE = "2077.1.1.1"                                          -- I myk fajrancik, czas na Falloucika
NDefines.NGame.MAP_SCALE_PIXEL_TO_KM = 0.2450                                   -- Yes, we also did the math
NDefines.NDiplomacy.NUM_DAYS_TO_ENABLE_KICKING_NEW_MEMBERS_OF_FACTION = 30      -- Nie wiem czemu ale można kogos wyjebać z frakcji po 30 dniach
NDefines.NDiplomacy.NUM_DAYS_TO_ENABLE_REINVITE_KICKED_NATIONS = 30             -- I z powrotem ich zaprosić po kolejnych 30, tylko ze kurwa mamy wylaczone to xd
NDefines.NDiplomacy.NOT_READY_FOR_WAR_BASE = -10                                -- AI nie powinno się az tak srać gdy dostaje call to war a nie jest ubrane
NDefines.NDiplomacy.FRONT_IS_DANGEROUS = -10                                    -- No nie bój się pizdo, dołączaj do wojny
NDefines.NCountry.MIN_FOCUSES_FOR_CONTINUOUS = 5                                -- Minimalna liczba focusów wymagana do odblokowania continuosów
NDefines.NCountry.MIN_STABILITY = -1.0                                          -- Mamy -100% stabilności...w vanillce jest min 0%
NDefines.NCountry.POPULATION_YEARLY_GROWTH_BASE = 0.005                         -- Przyrost naturalny populacji
NDefines.NPolitics.BASE_POLITICAL_POWER_INCREASE = 1.75                         -- Podstawowy przyrost PP
NDefines.NResistance.GARRISON_MANPOWER_REINFORCEMENT_SPEED = 200.0              -- Liczba o którą się odnawiają manpowerem garnizony, zmniejszona bo jednostki mamy mniejsze
NDefines.NProduction.MIN_POSSIBLE_TRAINING_MANPOWER = 10000                     -- How many deployment lines minimum can be training (co kurwa? to nie powinno być maximum ty szwedzki pachołku?)
NDefines.NResistance.COMPLIANCE_GROWTH_BASE	 = 0.2                              -- Podstawowy przyrost compliance
NDefines.NResistance.RESISTANCE_GROWTH_BASE	 = 0.05                             -- Podstawowy przyrost resistance
NDefines.NResistance.FOREIGN_MANPOWER_MIN_THRESHOLD = 500                       -- Jaki kurwa manpower transfer, co wy pierdolicie?
NDefines.NBuildings.INFRASTRUCTURE_RESOURCE_BONUS = 0                           -- Ten jebany bonus do surowców z infrastruktury
NDefines.NBuildings.SUPPLY_ROUTE_RESOURCE_BONUS = 0                             -- To samo tylko że z supply routów? Kurwa, jak kupujesz to kupujesz, nikt Ci nie dorzuci dodatkowego węgla debilu
NDefines.NBuildings.RADAR_RANGE_BASE = 40
NDefines.NBuildings.RADAR_RANGE_MIN = 40
NDefines.NBuildings.RADAR_RANGE_MAX = 360
NDefines.NProduction.ENERGY_SCALING_COST_BY_FACTORY_COUNT = 0.00001 -- Scales energy cost based on the total number of factories 0.0225
NDefines.NProduction.BASE_ENERGY_COST = 0.0						-- How much energy per factory consumes 0.25
NDefines.NMilitary.ARMOR_VS_AVERAGE = 0.3                                       -- jakiś bełkot (how to weight in highest armor & pen vs the division average)
NDefines.NMilitary.DIVISION_SIZE_FOR_XP = 4                                     -- ile batalionów powinna mieć jednostka żeby się liczyła jako pełnoprawna (coś do expa)
NDefines.NMilitary.PLAN_EXECUTE_CAREFUL_LIMIT = 10	                            -- coś z battle planami
NDefines.NMilitary.PLAN_EXECUTE_BALANCED_LIMIT = 0	                            -- coś z battle planami
NDefines.NMilitary.PLAN_EXECUTE_RUSH = -200                                     -- coś z battle planami
NDefines.NMilitary.PLAN_EXECUTE_SUPPLY_CHECK = { 0.1, 0.0, 0.0, 0.1, 0.0 }      -- coś z battle planami
NDefines.NMilitary.PLAN_COHESION_WEIGHTS = { 1.0, 50.0, 100.0, 200.0 }          -- coś z battle planami
NDefines.NMilitary.FIELD_EXPERIENCE_SCALE = 0.0015	                            -- coś z expem
NDefines.NMilitary.LEADER_EXPERIENCE_SCALE = 0.5                                -- coś z expem
NDefines.NMilitary.EXPERIENCE_COMBAT_FACTOR = 0.2                               -- coś z expem
NDefines.NMilitary.PLAN_SPREAD_ATTACK_WEIGHT = 16                               -- ponoć rozszerzanie frontu
NDefines.NMilitary.FRONTLINE_EXPANSION_FACTOR = 0.5                             -- żeby nie skręcali do sklepu po jabole
NDefines.NMilitary.PLAYER_ORDER_PLANNING_DECAY = 0.01                           -- to jest hit, jebanie gracza za to że mikruje XDDDDDDDDDDDDD
NDefines.NMilitary.GENERATE_AI_DIV_COMMAND_HISTORY_ENTRIES = false              -- nie ma medali dla jednostek ai
NDefines.NMilitary.OUT_OF_SUPPLY_ATTRITION = 0.25                               -- max attrition gdy nie masz supli                               
NDefines.NMilitary.WAR_SCORE_LOSSES_RATIO = 4                                   -- war score za każde 1000 trupów (chyba się dobrze skaluje)
NDefines.NMilitary.WAR_SCORE_PROVINCE_FACTOR = 4                                -- war score za prowki ale tylko za jej pierwsze zdobycie????
NDefines.NMilitary.VPS_FOR_HISTORY_ENTRY = 10                                   -- za jaki vp jednostka dostaje medal
NDefines.NMilitary.VPS_FOR_HIGH_HISTORY_ENTRY = 30                              -- za jaki vp jednostka dostaje virtuti militari 
NDefines.NMilitary.PLAN_MIN_AUTOMATED_EMPTY_POCKET_SIZE = 20                    -- kociołki panoramixa
NDefines.NAI.VP_LEVEL_IMPORTANCE_HIGH = 2	
NDefines.NAI.UNIT_ASSIGNMENT_TERRAIN_IMPORTANCE = 1.0	
NDefines.NAI.ASSIGN_FRONT_TERRAIN_MOVEMENT_FACTOR = 0
NDefines.NAI.ASSIGN_FRONT_TERRAIN_DEFENSE_FACTOR = 0
NDefines.NAI.VP_LEVEL_IMPORTANCE_MEDIUM = 1 	
NDefines.NAI.VP_LEVEL_IMPORTANCE_LOW = 1			
NDefines.NAI.PLAN_ACTIVATION_MAJOR_WEIGHT_FACTOR = 1	
NDefines.NAI.PLAN_ACTIVATION_PLAYER_WEIGHT_FACTOR = 1 	
NDefines.NAI.MANPOWER_RESERVED_THRESHOLD = 0.20
NDefines.NAI.PLAN_FACTION_STRONG_TO_EXECUTE = 0.6 --0.80	0.60		        -- % or more of units in an order to consider ececuting the plan
NDefines.NAI.PLAN_MIN_SIZE_FOR_FALLBACK = 600
NDefines.NAI.ORG_UNIT_STRONG = 0.75												-- Organization % for unit to be considered strong
NDefines.NAI.STR_UNIT_STRONG = 0.75												-- Strength (equipment) % for unit to be considered strong
NDefines.NAI.PLAN_FACTION_NORMAL_TO_EXECUTE = 0.65
NDefines.NAI.ORG_UNIT_NORMAL = 0.6 --6												-- Organization % for unit to be considered normal
NDefines.NAI.STR_UNIT_NORMAL = 0.6 --6												-- Strength (equipment) % for unit to be considered normal
NDefines.NAI.PLAN_FACTION_WEAK_TO_ABORT = 0.3 --0.50		0.65		        -- % or more of units in an order to consider ececuting the plan
NDefines.NAI.ORG_UNIT_WEAK = 0.45 --0.45												-- Organization % for unit to be considered weak
NDefines.NAI.STR_UNIT_WEAK = 0.4 --0.45												-- Strength (equipment) % for unit to be considered weak
NDefines.NAI.MIN_INVASION_PLAN_VALUE_TO_EXECUTE = 0.05                          -- minimalny szacunek sił do puszczenia inwazji
NDefines.NAI.MIN_INVASION_ORG_FACTOR_TO_EXECUTE = 0.2                           -- minimalna organizacja do puszczenia inwazji
NDefines.NAI.NAVAL_MISSION_INVASION_BASE = 2000                                 -- jakieś punkty, ale kurwa nie wiem do czego
NDefines.NAI.AREA_DEFENSE_SETTING_VP = false
NDefines.NAI.AREA_DEFENSE_SETTING_COASTLINES = false
NDefines.NAI.AREA_DEFENSE_BASE_IMPORTANCE = 10	
NDefines.NAI.STATE_CONTROL_FOR_AREA_DEFENSE = 1.00
NDefines.NAI.MAX_DISTANCE_NAVAL_INVASION = 2000.0                                -- te wyżej to chuj wie, ale to maksymalny dystans inwazji morskiej
NDefines.NAI.NAVAL_MISSION_DISTANCE_BASE = 4500
NDefines.NAI.AGGRESSIVENESS_BONUS_FOR_FRONTS_THAT_ARE_ON_HIGH_AGGRESSIVENESS = -0.6 -- UGRYŹ, ZAGRYŹ
NDefines.NAI.AGGRESSIVENESS_CHECK_BASE = 1                                      -- Baza - pisał Stalin posyłając cały swój front na aggresive stance
NDefines.NAI.AGGRESSIVENESS_CHECK_CAREFUL = 0.3                                 -- OSTROŻNIE!
NDefines.NAI.FRONT_EVAL_UNIT_SUPPLY_AND_ORG_LACK_IMPACT = 0.5                   -- URRRAAAAAAAAAAAAAAAAAA
NDefines.NAI.PLAN_VALUE_TO_EXECUTE = 0.01
NDefines.NAI.DEPLOY_MIN_TRAINING_SURRENDER_FACTOR = 0.4
NDefines.NAI.DEPLOY_MIN_EQUIPMENT_SURRENDER_FACTOR = 0.7
NDefines.NAI.EASY_TARGET_FRONT_IMPORTANCE = 15
NDefines.NAI.ATTACK_HEAVILY_DEFENDED_LIMIT = 0.2
NDefines.NAI.PLAN_ACTIVATION_SUPERIORITY_AGGRO = 1.0                            -- zraz obranego planu nie zawracaj w fallback line, nie opuszczaj wiary w force attack
NDefines.NAI.DEPLOY_MIN_TRAINING_WAR_FACTOR = 0.6                                   
NDefines.NSupply.VP_TO_SUPPLY_BASE = 0.35                                       -- halo baza, jakiś vp się tu kręci
NDefines.NMilitary.BORDER_WAR_VICTORY = 0.65                                    -- przy jakim balansie wygrywamy border wara (jest niski bo to głównie lorowe rzeczy)
NDefines.NMilitary.BORDER_WAR_WIN_DAYS_AGAINST_EMPTY_OPPONENTS = 7              -- nikt nie przyszedł na border wara ja pierdole
NDefines.NSupply.MAX_RAILWAY_LEVEL = 5    
NDefines.NOperatives.AGENCY_OPERATIVE_RECRUITMENT_TIME = 3                      -- sram na ciebie śledzioidzie skandynawski
